#!/usr/bin/env python3

from pptx import Presentation
from pptx.util import Inches, Pt

prs = Presentation()
title_slide_layout = prs.slide_layouts[5]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
title.text = "Here's a nice video!"


slide.shapes.add_movie("waterdrop.mp4",Inches(1), Inches(1.5),Inches(8),Inches(5))

prs.save('videotest.pptx')